### ISSUE TITLE
Obtaining a hystreet API key

### ISSUE THREAD

**Issue by jobreu** [JohannesFriedrich/hystReet#4]
I know that this is not an issue directly related to the package, but I was unable to find the API key after signing up for a hystreet account. Maybe you could extend/update the ReadMe/the "Getting started" vignette in that regard?

**Comment by JohannesFriedrich** [comment]
done with https://github.com/JohannesFriedrich/hystReet/commit/260feadce3c56b129539d562094009969cd6f4ae
